// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCmUYK5hDX1tPDoMVOHtxBLKNz05DFjo',
    appId: '1:740395228894:web:6d9097a1b0ebd6ed68ec4f',
    messagingSenderId: '740395228894',
    projectId: 'greenscan-a8e36',
    authDomain: 'greenscan-a8e36.firebaseapp.com',
    storageBucket: 'greenscan-a8e36.firebasestorage.app',
    measurementId: 'G-WEWGM56MCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAjyH9DAZuBqKOB-YSv0wbrLMv55u93fQ',
    appId: '1:740395228894:android:de72991c7adc368a68ec4f',
    messagingSenderId: '740395228894',
    projectId: 'greenscan-a8e36',
    storageBucket: 'greenscan-a8e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AUSO0HPofw-9umqSZ8b4Pv1HIli8Qw4',
    appId: '1:740395228894:ios:6416dbefa99822fa68ec4f',
    messagingSenderId: '740395228894',
    projectId: 'greenscan-a8e36',
    storageBucket: 'greenscan-a8e36.firebasestorage.app',
    iosBundleId: 'com.example.greenscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1AUSO0HPofw-9umqSZ8b4Pv1HIli8Qw4',
    appId: '1:740395228894:ios:6416dbefa99822fa68ec4f',
    messagingSenderId: '740395228894',
    projectId: 'greenscan-a8e36',
    storageBucket: 'greenscan-a8e36.firebasestorage.app',
    iosBundleId: 'com.example.greenscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfCmUYK5hDX1tPDoMVOHtxBLKNz05DFjo',
    appId: '1:740395228894:web:57a1653eb4197caf68ec4f',
    messagingSenderId: '740395228894',
    projectId: 'greenscan-a8e36',
    authDomain: 'greenscan-a8e36.firebaseapp.com',
    storageBucket: 'greenscan-a8e36.firebasestorage.app',
    measurementId: 'G-EMX5Y1XR44',
  );
}
